@startuml F1c_AssignOM_Sequence
title Figure F1c — [Optional] Assign / Change Operation Manager

skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true

actor Admin
participant "Front-end" as FE
participant "PropertyOnboardingController" as C
participant "PropertyOnboardingServiceImpl" as S
participant "OperationManagementRepository" as OMR
participant "PropertyRepository" as PR
database DB

opt [PENDING_OPERATION_MANAGER or change OM when ACTIVE/RENTED]
  Admin -> FE : (1) Select / change manager
  activate Admin
  activate FE
  FE -> C : (2) PATCH /api/v1/properties/{id}/operation-manager
  activate C
  C -> S : (3) assignOperationManager(id, req)
  activate S
  S -> DB : (4) BeginTransaction()
  activate DB
  S -> OMR : (5) upsert ZoneManager / OM
  activate OMR
  OMR -> DB : (6) INSERT/UPDATE
  DB --> OMR : (7) return OK
  OMR --> S : (8) return OK
  deactivate OMR
  S -> PR : (9) save(operationManagerId,\nPENDING_OPERATION_MANAGER→ACTIVE)
  activate PR
  PR -> DB : (10) UPDATE Property
  DB --> PR : (11) return OK
  PR --> S : (12) return Property
  deactivate PR
  S -> DB : (13) CommitTransaction()
  DB --> S : (14) return Committed
  deactivate DB
  S --> C : (15) return PropertyActivationResponse
  deactivate S
  C --> FE : (16) return Response
  deactivate C
  FE --> Admin : (17) return OM assigned
  deactivate FE
  deactivate Admin
end

@enduml
